%% From http://projecteuler.net/index.php?section=problems&id=2
%% Find the sum of all the even-valued terms in the Fibonacci sequence which do not exceed four million.
%% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%% Find the sum of all the even-valued terms in the sequence which do not exceed four million


-module(pb2).
-export([pb2/0, fibos/1]).

pb2()-> lists:sum(values(1)).

values(N) -> 
    Z=fibo(N),
    if Z =< 4000000 andalso Z rem 2 =:=0 -> [Z | values(N+1) ];
       Z =< 4000000  -> values(N+1);
	   true -> []
    end.

    
fibos(1) -> [1];
fibos(N) ->
    [fibo(N) | fibos(N-1)].

fibo(0) -> 0 ;
fibo(1) -> 1 ;	  
fibo(X)-> fibo(X-1) + fibo(X-2).
