%% After 40755, what is the next triangle number that is also pentagonal and hexagonal?
%% Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
%% Triangle 	  	T_(n)=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
%% Pentagonal 	  	P_(n)=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
%% Hexagonal 	  	H_(n)=n(2n−1) 	  	1, 6, 15, 28, 45, ...

%% It can be verified that T_(285) = P_(165) = H_(143) = 40755.

%% Find the next triangle number that is also pentagonal and hexagonal.
-module(pb45).
-export([pb45/0, pb45/1]).


triangle (N) ->
    (N * ( N + 1)) div 2 .

pentagonal (N) ->
    (N * (3 * N - 1)) div 2.
hexagonal (N) ->
    N * (2 * N -1).
pb45()->
    pb45(286).
pb45(Number)->
    {X, Y, Z} = search ({Number, 1, 1}),
    io:format ( "Found for : ~p~n~nNumber is : ~p~n", [{X, Y, Z}, triangle (X)]).

search({IndexT, IndexP, IndexH})->
    X=triangle(IndexT), 
    Y=pentagonal(IndexP), 
    Z=hexagonal(IndexH),
    if  X > Y -> search({IndexT, IndexP + 1 , IndexH}) ;
	X > Z -> search({IndexT, IndexP, IndexH + 1 }) ;
	X < Y orelse X < Z -> search({IndexT +1, IndexP, IndexH});
	true -> {IndexT, IndexP, IndexH}
    end.
